apiVersion: v1
kind: Pod
metadata:
  name: grpc-client
spec:
  priorityClassName: system-node-critical
  containers:
  - name: grpc-client
    command: ["sh", "-c"]
    args: ["while true ; do sleep 5 ; done"]
    image: gcr.io/directpath-test-images/grpc_interop_go1.11:v1.21.0
    imagePullPolicy: Always
