apiVersion: v1
kind: ResourceQuota
metadata:
    name: all-critical-pods
    namespace: default
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
spec:
  hard:
    pods: "100"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["system-node-critical", "system-cluster-critical"]
